### ISSUE TITLE
pip install latest release not available

### ISSUE THREAD

**Issue by TMW-bioinformatics** [wavefrontshaping/ALP4lib#16]
Dear Sébastien,
could you make release 1.0.0 available for installation with pip, currently I get following message:

pip install ALP4lib==1.0.0
ERROR: Could not find a version that satisfies the requirement ALP4lib==1.0.0 (from versions: 0.0.2, 0.0.3, 0.0.3.post1, 0.0.3.post2, 0.0.4.1, 0.0.5)
ERROR: No matching distribution found for ALP4lib==1.0.0

Thanks!

**Comment by wavefrontshaping** [comment]
Hi,

> could you make release 1.0.0 available for installation with pip

Will do, but in the meantime, you can always install the latest version of the code with
`pip install git+https://github.com/wavefrontshaping/ALP4lib.git`
