### ISSUE TITLE
3 Errors found.

### ISSUE THREAD

**Issue by Bdemirel-cpu** [wavefrontshaping/ALP4lib#22]
Here are 3 minor errors I found in ALP4.py (v 1.0.1).

**Line 377**: libDir = (_winreg.QueryValueEx(key, "Path"))[0] + "/ALP-{0} API/".format(version)

I don't have such a folder: "/ALP-{0} high-speed API/"  for example does work.

**Line 397**: libPath += 'alpD41.dll'
This was mentioned already, but it should say: “alpV42” 

**Line 894**:  self._checkError(self._ALPLib.AlpDevControlEx(self.ALP_ID, controlType, userStruct.byref()),
                         'Error sending request.')

The command userStruct.byref() should be replaced by: ct.byref(userStruct) .

**Comment by wavefrontshaping** [comment]
Sorry for the delay, I implemented those changes. Thanks.
