### ISSUE TITLE
Module not importing under Anaconda (Python 3.6.4)

### ISSUE THREAD

**Issue by ruilvo** [wavefrontshaping/ALP4lib#4]
Hey!

I installed the module using` pip`, using `easy_install` and using `python setup.py install` and regardless of what I do I always get:
```
In [1]: import ALP4
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-300cfabdcbaf> in <module>()
----> 1 import ALP4

ModuleNotFoundError: No module named 'ALP4'
```

`pip` says: 
`Requirement already satisfied: ALP4lib in c:\anaconda3\lib\site-packages`

But the error persists regardless...

Thank you by all your work!

**Comment by lordkalma** [comment]
Usable using the ALP4.py file as "file module".
I put the ALP4.py file alongside my main file and I could import it and use it.
Other bugs found.

**Comment by dboonz** [comment]
I fixed this in my version, you have to add 
```package_dir={'': 'src'},``` to setup.py arguments. 

I submitted a pull request so will probably be fixed soon :).
cheers!
Dirk
