### ISSUE TITLE
Version 4.2 bad DLL import

### ISSUE THREAD

**Issue by ruilvo** [wavefrontshaping/ALP4lib#5]
On ALP4.py:
lines 333, 334:
```
        elif (version == '4.2'):
            libPath += 'alpD41.dll'
```
The DLL name is wrong. Should be `alpV42.dll` or `alpV42basic.dll` depending of basic or high-speed API. 

I imported `alpV42.dll` and it's working even though I'm not sure I have the basic or HS API access...

**Comment by wavefrontshaping** [comment]
Updated. Thanks
