### ISSUE TITLE
Function DevInquire tries to call return value

### ISSUE THREAD

**Issue by ruilvo** [wavefrontshaping/ALP4lib#6]
On line 627 `return ret.value()` should probably be `return ret.value`

(I'd make a pull request if I only knew how to use git decently)

**Comment by guilhermebene** [comment]
To me it still seems to be a problem, even though it has remained like this for quite some time.
I might make a pull request to solve it.
Moreover, it seems that the return should be of type `c_long` instead of `c_double`, according to my version of the ALP-4 documentations.
